### ISSUE TITLE
网站显示会出现卡死的状况, 是tornado http server的问题?

### ISSUE THREAD

**Issue by halida** [halida/snake-challenge#58]
RT

**Comment by halida** [comment]
File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 367, in _run_callback
    callback(_args, *_kwargs)
  File "web_server.py", line 107, in check_info
    cls.send_info(room, data[i:])
  File "web_server.py", line 113, in send_info
    c.write_message(info)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 104, in write_message
    self.ws_connection.write_message(message)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 321, in write_message
    self.stream.write(b("\x00") + message + b("\xff"))
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 213, in write
    self._check_closed()
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 507, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
2011-12-14 09:16:56,487 - ERROR - Exception in I/O handler for fd <zmq.core.socket.Socket object at 0x2a51a10>
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/ioloop.py", line 333, in start
    self._handlers[fd](fd, events)
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 393, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 426, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 367, in _run_callback
    callback(_args, *_kwargs)
  File "web_server.py", line 107, in check_info
    cls.send_info(room, data[i:])
  File "web_server.py", line 113, in send_info
    c.write_message(info)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 104, in write_message
    self.ws_connection.write_message(message)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 321, in write_message
    self.stream.write(b("\x00") + message + b("\xff"))
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 213, in write
    self._check_closed()
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 507, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
2011-12-14 09:18:54,680 - WARNING - Read error on 23: [Errno 110] Connection timed out
2011-12-14 09:55:14,151 - INFO - 200 POST /cmd (50.56.97.47) 220.93ms

**Comment by halida** [comment]
```
self.stream.write(b("\x00") + message + b("\xff"))
```

  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 213, in write
    self._check_closed()
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 507, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
2011-12-15 08:14:09,649 - ERROR - Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 393, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 426, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 367, in _run_callback
    callback(_args, *_kwargs)
  File "web_server.py", line 107, in check_info
    cls.send_info(room, data[i:])
  File "web_server.py", line 113, in send_info
    c.write_message(info)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 104, in write_message
    self.ws_connection.write_message(message)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 321, in write_message
    self.stream.write(b("\x00") + message + b("\xff"))
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 213, in write
    self._check_closed()
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 507, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
2011-12-15 08:14:09,650 - ERROR - Exception in I/O handler for fd <zmq.core.socket.Socket object at 0x1b82a10>
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/ioloop.py", line 333, in start
    self._handlers[fd](fd, events)
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 393, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 426, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.6/dist-packages/pyzmq-2.1.10-py2.6-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 367, in _run_callback
    callback(_args, *_kwargs)
  File "web_server.py", line 107, in check_info
    cls.send_info(room, data[i:])
  File "web_server.py", line 113, in send_info
    c.write_message(info)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 104, in write_message
    self.ws_connection.write_message(message)
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/websocket.py", line 321, in write_message
    self.stream.write(b("\x00") + message + b("\xff"))
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 213, in write
    self._check_closed()
  File "/usr/local/lib/python2.6/dist-packages/tornado-2.1.1git-py2.6.egg/tornado/iostream.py", line 507, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed

**Comment by halida** [comment]
跑了几天没有问题. 看起来是这个地方的问题, tornado本身很给力.
